name: 10Build OTX Server  
on: [push, pull_request]  
  
jobs:  
  build:  
    runs-on: windows-latest  
    steps:  
      - uses: actions/checkout@v4  
        
      - name: Install Boost via Chocolatey  
        run: |  
          choco install boost-msvc-14.3 --version=1.84.0 -y  
          # Criar link simbólico para o caminho esperado pelo projeto  
          if (!(Test-Path "C:\local")) { New-Item -ItemType Directory -Path "C:\local" }  
          if (!(Test-Path "C:\local\boost_1_84_0")) {  
            New-Item -ItemType SymbolicLink -Path "C:\local\boost_1_84_0" -Target "C:\ProgramData\chocolatey\lib\boost-msvc-14.3\tools"  
          }  
        shell: powershell  
          
      - name: Setup MSBuild  
        uses: microsoft/setup-msbuild@v2  
          
      - name: Build  
        run: msbuild sources/msvc/TheOTXServer.vcxproj /p:Configuration=Release /p:Platform=x64 /m  
          
      - name: Upload Artifact  
        uses: actions/upload-artifact@v4  
        with:  
          name: TheOTXServer  
          path: sources/msvc/x64/Release/TheOTXServer.exe
