name: Build OTX Server 2 with MSVC  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: windows-latest  
      
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
        
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v1.3  
        
    - name: Setup Visual Studio  
      uses: ilammy/msvc-dev-cmd@v1  
      with:  
        arch: x64  
          
    - name: Download and Install Boost 1.84.0  
      run: |  
        Invoke-WebRequest -Uri "https://sourceforge.net/projects/boost/files/boost-binaries/1.84.0/boost_1_84_0-msvc-14.3-64.exe/download" -OutFile "boost_installer.exe"  
        Start-Process -FilePath "boost_installer.exe" -ArgumentList "/S", "/D=C:\local\boost_1_84_0" -Wait  
          
    - name: Verify Boost Installation  
      run: |  
        if (Test-Path "C:\local\boost_1_84_0\lib64-msvc-14.3") {  
          Write-Host "Boost libraries found"  
          Get-ChildItem "C:\local\boost_1_84_0\lib64-msvc-14.3" | Select-Object -First 5  
        } else {  
          Write-Error "Boost installation failed"  
          exit 1  
        }  
          
    - name: Build OTX Server 2  
      run: |  
        msbuild sources/msvc/TheOTXServer.vcxproj /p:Configuration=Release /p:Platform=x64 /m  
          
    - name: Upload Build Artifacts  
      uses: actions/upload-artifact@v4  
      with:  
        name: otx-server-2-build  
        path: |  
          sources/msvc/x64/Release/TheOTXServer.exe  
          sources/msvc/x64/Release/*.dll
