name: Build OTX Server 2 with MSVC (Direct Download)  
  
on:  
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build:  
    runs-on: windows-latest  
      
    steps:  
    - name: Checkout code  
      uses: actions/checkout@v4  
        
    - name: Setup MSBuild  
      uses: microsoft/setup-msbuild@v1.3  
        
    - name: Setup Visual Studio  
      uses: ilammy/msvc-dev-cmd@v1  
      with:  
        arch: x64  
          
    - name: Cache Boost  
      id: cache-boost  
      uses: actions/cache@v3  
      with:  
        path: C:\local\boost_1_84_0  
        key: boost-1.84.0-msvc-14.3-x64-direct  
          
    - name: Download and Install Boost 1.84.0 (Direct Link)  
      if: steps.cache-boost.outputs.cache-hit != 'true'  
      run: |  
        # [Script da Solução 1 acima]  
          
    - name: Verify Boost Installation  
      run: |  
        if (Test-Path "C:\local\boost_1_84_0\lib64-msvc-14.3") {  
          Write-Host "Boost libraries found"  
          Get-ChildItem "C:\local\boost_1_84_0\lib64-msvc-14.3" | Select-Object -First 5  
        } else {  
          Write-Error "Boost installation failed"  
          exit 1  
        }  
          
    - name: Build OTX Server 2  
      run: |  
        msbuild sources/msvc/TheOTXServer.vcxproj /p:Configuration=Release /p:Platform=x64 /m
