name: Build OTX Server 2 - Windows  
on:   
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build-windows:  
    runs-on: windows-2022  
      
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  
          
      - name: Setup MSBuild  
        uses: microsoft/setup-msbuild@v1.3  
          
      - name: Install Boost via vcpkg  
        run: |  
          git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg  
          C:\vcpkg\bootstrap-vcpkg.bat  
          C:\vcpkg\vcpkg install boost:x64-windows  
            
      - name: Setup Boost directory structure  
        run: |  
          mkdir C:\local\boost_1_84_0 -Force  
          xcopy /E /I "C:\vcpkg\installed\x64-windows\include\boost" "C:\local\boost_1_84_0\"  
          xcopy /E /I "C:\vcpkg\installed\x64-windows\lib" "C:\local\boost_1_84_0\lib64-msvc-14.3\"  
            
      - name: Verify SDK and create missing directories  
        run: |  
          if (!(Test-Path "sources\otx-windows-sdk\lua\lib64")) {  
            Write-Host "Creating missing lib64 directories..."  
            mkdir sources\otx-windows-sdk\lua\lib64 -Force  
            mkdir sources\otx-windows-sdk\libxml2\lib64 -Force  
            mkdir sources\otx-windows-sdk\sqlite3\lib64 -Force  
            mkdir sources\otx-windows-sdk\openssl\lib64 -Force  
            mkdir sources\otx-windows-sdk\mysql-connector-c\lib64 -Force  
            mkdir sources\otx-windows-sdk\mpir\lib64 -Force  
            mkdir sources\otx-windows-sdk\libiconv\lib64 -Force  
          }  
            
      - name: Build project  
        run: |  
          msbuild sources/msvc/TheOTXServer.vcxproj /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143  
            
      - name: Upload artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: otx-server-windows-x64  
          path: sources/msvc/x64/Release/TheOTXServer.exe
