name: Build OTX Server 2 - Windows  
on:   
  push:  
    branches: [ main, master ]  
  pull_request:  
    branches: [ main, master ]  
  
jobs:  
  build-windows:  
    runs-on: windows-2022  
      
    steps:  
      - name: Checkout repository  
        uses: actions/checkout@v4  
          
      - name: Setup MSBuild  
        uses: microsoft/setup-msbuild@v1.3  
          
      - name: Setup Boost 1.84.0  
        run: |  
          # Download Boost específico para o caminho esperado  
          Invoke-WebRequest -Uri "https://github.com/actions/boost-versions/releases/download/1.84.0-20231205.1/boost-1.84.0-win32-msvc14.3-x64.tar.gz" -OutFile "boost.tar.gz"  
          tar -xzf boost.tar.gz -C C:\  
          move C:\boost_1_84_0 C:\local\boost_1_84_0  
            
      - name: Verify SDK structure  
        run: |  
          if (!(Test-Path "sources\otx-windows-sdk\lua\lib64")) {  
            Write-Host "Creating missing lib64 directories..."  
            mkdir sources\otx-windows-sdk\lua\lib64 -Force  
            mkdir sources\otx-windows-sdk\libxml2\lib64 -Force  
            mkdir sources\otx-windows-sdk\sqlite3\lib64 -Force  
            mkdir sources\otx-windows-sdk\openssl\lib64 -Force  
            mkdir sources\otx-windows-sdk\mysql-connector-c\lib64 -Force  
            mkdir sources\otx-windows-sdk\mpir\lib64 -Force  
            mkdir sources\otx-windows-sdk\libiconv\lib64 -Force  
          }  
            
      - name: Build project  
        run: |  
          msbuild sources/msvc/TheOTXServer.vcxproj /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v143  
            
      - name: Upload artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: otx-server-windows-x64  
          path: sources/msvc/x64/Release/TheOTXServer.exe
